name: almacen_app
description: "Mobilink Almacén - Gestión de traspasos de neumáticos"
publish_to: 'none'
version: 1.2.1+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_horizontal.png
